### ISSUE TITLE
Add slug for animals

### ISSUE THREAD

**Issue by michaelbina** [white-rabbit-apps/reshare-web#67]
/animal/angel

use the same rules as for usernames for duplicates

**Comment by chileap** [comment]
@michaelbina I have question with "use the same rules as for usernames for duplicates". Does it mean we need to validate uniqueness with name too?

**Comment by michaelbina** [comment]
@chileap no.  animal usernames should not be unique.  Sorry this wasn't clear and I just checked and there are no slugs for users yet  so I understand if this was confusing.  I just looked at the GitHub for the slug gem we are using (https://github.com/bkoski/slug) and it says "If a slug already exists, Slug will automatically append a '-n' suffix to your slug to make it unique. The second instance of a slug is '-1'."

So I guess just use the library as it is and it will automatically take care of duplicate slugs and append a number.  Unless you can think of a better way, lets go with that for now.
