### ISSUE TITLE
Import breeds data

### ISSUE THREAD

**Issue by michaelbina** [white-rabbit-apps/reshare-web#82]
Data is in the json file.  Import it into the DB

[Breed.txt](https://github.com/white-rabbit-apps/reshare-web/files/4412091/Breed.txt)

**Comment by michaelbina** [comment]
Import the data in the json file.  Make sure to add any missing fields to the db to get all the data.

**Comment by michaelbina** [comment]
Here are the images [breeds.zip](https://github.com/white-rabbit-apps/reshare-web/files/4550000/breeds.zip)

**Comment by michaelbina** [comment]
Ideal would be to have a script that does the work, so we can do it on the production machine.

**Comment by chileap** [comment]
@michaelbina I have problem when I saved record, they said `Species must exist` I wonder if we can set it as optional or not? For Species
